"use server"

import OpenAI from "openai"
import { createClient } from "@supabase/supabase-js"
import { revalidatePath } from "next/cache" 

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
})

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
const supabaseKey = supabaseServiceRoleKey || supabaseAnonKey

const supabase = supabaseUrl && supabaseKey 
  ? createClient(supabaseUrl, supabaseKey, {
      auth: { autoRefreshToken: false, persistSession: false }
    })
  : null

export interface ScrapeResult {
  company: string
  role: string
  location: string
  summary: string
  score?: number
  pros?: string[]
  cons?: string[]
  error?: string 
}

export async function scrapeJobListing(input: string, type: "url" | "text", userId: string): Promise<ScrapeResult | { error: string } | null> {
  console.log(`🔍 STARTING ${type.toUpperCase()} SCRAPE for User: ${userId}`)
  
  if (!supabase) return { error: "Database configuration error" }

  // 1. Fetch Profile & Resume
  const { data: profile } = await supabase
    .from('profiles')
    .select('is_pro, scrape_count, resume_text, school, major') 
    .eq('id', userId)
    .single()

  const isPro = profile?.is_pro || false
  const scrapeCount = profile?.scrape_count || 0

  // 2. Safeguard: Check Limits
  if (type === "url" && !isPro && scrapeCount >= 5) {
    console.warn("❌ LIMIT REACHED")
    return { error: "limit_reached" } 
  }

  try {
    // 3. Get Content (URL or Text)
    let textContent = ""
    let sourceUrl = type === "url" ? input : "Manual Entry"

    if (type === "url") {
      if (!input || !input.startsWith("http")) throw new Error(`Invalid URL: ${input}`)
      
      const response = await fetch(input, {
        headers: { "User-Agent": "Mozilla/5.0" },
      })
      if (!response.ok) throw new Error(`Failed to fetch URL`)
      
      const html = await response.text()
      // Clean up HTML aggressively to save input tokens
      textContent = html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 8000)
    } else {
      textContent = input.slice(0, 8000)
    }

    if (textContent.length < 50) throw new Error("Content is too short")

    // 4. Construct Dynamic Prompt (Cheapest Way: 1 Call)
    // If Pro & Resume exists, we ask for Analysis + Extraction.
    // If not, we ONLY ask for Extraction (saving tokens).
    
    const canAnalyze = isPro && profile?.resume_text;
    
    let systemPrompt = "";
    let userMessage = "";

    if (canAnalyze) {
      systemPrompt = `You are an expert technical recruiter. 
      Analyze the provided CANDIDATE RESUME against the JOB LISTING.
      
      RETURN JSON ONLY with these keys:
      - company: string
      - role: string
      - location: string (City, State or "Remote")
      - summary: string (2-4 sentences)
      - score: number (0-100 fit score)
      - pros: string[] (3 key strengths of the candidate for this role)
      - cons: string[] (3 potential gaps or weaknesses)
      
      Do NOT generate interview questions or action plans yet.`

      userMessage = `CANDIDATE: Major: ${profile.major}, School: ${profile.school}
      RESUME: ${profile.resume_text.slice(0, 4000)}
      
      JOB LISTING:
      ${textContent}`
    } else {
      systemPrompt = `You are a job extraction assistant. Extract structured data.
      RETURN JSON ONLY:
      { "company": "string", "role": "string", "location": "string", "summary": "string" }`
      
      userMessage = `JOB LISTING: ${textContent}`
    }

    // 5. Single AI Call (Using gpt-5-nano as requested)
    const completion = await openai.chat.completions.create({
      model: "gpt-5-nano", 
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userMessage },
      ],
      response_format: { type: "json_object" },
    })

    const result = JSON.parse(completion.choices[0].message.content || "{}") as ScrapeResult

    // 6. Save to DB
    const { error: insertError } = await supabase
      .from("internships")
      .insert({
        user_id: userId,
        company: result.company,
        role: result.role,
        location: result.location,
        summary: result.summary,
        source_url: sourceUrl,
        status: 'Wishlist',
        
        // Save Scores/Analysis if they exist
        fit_score: result.score || null,
        fit_analysis: canAnalyze ? {
          pros: result.pros,
          cons: result.cons
          // questions & action_plan are intentionally left undefined 
          // to be generated by the "Generate" button later.
        } : null,

        created_at: new Date().toISOString(),
      })

    if (insertError) {
      console.error("❌ DB Insert Error:", insertError.message)
    } else {
      // Increment count for free users
      if (type === "url") {
         await supabase
          .from('profiles')
          .update({ scrape_count: scrapeCount + 1 })
          .eq('id', userId)
      }

      revalidatePath('/dashboard') 
      console.log("✅ Saved with Score & Analysis")
    }

    return result
  } catch (error) {
    console.error("❌ ERROR:", error)
    return null
  }
}